name: Run e2e tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: cache node_modules
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

        if: steps.pnpm-cache.outputs.cache-hit != 'true'
      - run: pnpm install --prefer-offline --frozen-lockfile

      - name: cypress run
        uses: cypress-io/github-action@v6
        env:
          APP_URL: "http://localhost:3000/"
          NEXT_PUBLIC_API_BASE_URL: "https://ignite-devstore.vercel.app/"
        with:
          build: npm run build
          start: npm start
